# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbd2f177efc1f43edede998f3c6a0dc25d5c1c590bcdd7f939e738b07d41a0f33606bfd3bfab1b42649861ff8ee74fa60db543d617e199e3a4e4937613661204

test:
  secret_key_base: 2eb15af2faeef33aa19de1b793c0a49bba75fc93a367545dafc29c4ecc277d5482758010550a8de93f924d8870dcf013a65bb4453845e7ea2287e15251359416

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
